# Generated by Django 5.1.2 on 2024-11-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('menu_name', models.CharField(max_length=100)),
                ('items', models.JSONField()),
            ],
        ),
    ]
