# Generated by Django 5.1.2 on 2024-11-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myway', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combination',
            old_name='user_name',
            new_name='menu_brand',
        ),
    ]
